Resources:
  CreditsCreditsStoreDC9BDB5C:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: EcgStack/Credits/CreditsStore/Resource
  CreditsCreditsStorePolicy1E105647:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: CreditsCreditsStoreDC9BDB5C
      PolicyDocument:
        Statement:
          - Action: s3:*
            Condition:
              Bool:
                aws:SecureTransport: 'false'
            Effect: Deny
            Principal: '*'
            Resource:
              Fn::Join:
                - ''
                - - Fn::GetAtt:
                      - CreditsCreditsStoreDC9BDB5C
                      - Arn
                  - /*
        Version: '2012-10-17'
    Metadata:
      aws:cdk:path: EcgStack/Credits/CreditsStore/Policy/Resource
  CreditsCreditsHandlerServiceRole96F860B7:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
        - Fn::Join:
            - ''
            - - 'arn:'
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: EcgStack/Credits/CreditsHandler/ServiceRole/Resource
  CreditsCreditsHandlerServiceRoleDefaultPolicyF2B38D20:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
              - s3:DeleteObject*
              - s3:PutObject
              - s3:Abort*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - CreditsCreditsStoreDC9BDB5C
                  - Arn
              - Fn::Join:
                  - ''
                  - - Fn::GetAtt:
                        - CreditsCreditsStoreDC9BDB5C
                        - Arn
                    - /*
        Version: '2012-10-17'
      PolicyName: CreditsCreditsHandlerServiceRoleDefaultPolicyF2B38D20
      Roles:
        - Ref: CreditsCreditsHandlerServiceRole96F860B7
    Metadata:
      aws:cdk:path: EcgStack/Credits/CreditsHandler/ServiceRole/DefaultPolicy/Resource
  CreditsCreditsHandler3E4C260D:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters85999cde342a3a55cb865b24fc98c0f87f12ed970badb944f4af9e6a009ccb3eS3Bucket2E82DD27
        S3Key:
          Fn::Join:
            - ''
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - '||'
                      - Ref: AssetParameters85999cde342a3a55cb865b24fc98c0f87f12ed970badb944f4af9e6a009ccb3eS3VersionKey614CE18A
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - '||'
                      - Ref: AssetParameters85999cde342a3a55cb865b24fc98c0f87f12ed970badb944f4af9e6a009ccb3eS3VersionKey614CE18A
      Role:
        Fn::GetAtt:
          - CreditsCreditsHandlerServiceRole96F860B7
          - Arn
      Environment:
        Variables:
          BUCKET:
            Ref: CreditsCreditsStoreDC9BDB5C
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
      Handler: index.postCredits
      Runtime: nodejs14.x
    DependsOn:
      - CreditsCreditsHandlerServiceRoleDefaultPolicyF2B38D20
      - CreditsCreditsHandlerServiceRole96F860B7
    Metadata:
      aws:cdk:path: EcgStack/Credits/CreditsHandler/Resource
      aws:asset:path: asset.85999cde342a3a55cb865b24fc98c0f87f12ed970badb944f4af9e6a009ccb3e
      aws:asset:property: Code
  Creditscreditsapi548AF886:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: This service serves widgets.
      Name: Credits Service
    Metadata:
      aws:cdk:path: EcgStack/Credits/credits-api/Resource
  CreditscreditsapiCloudWatchRoleF4FE0D51:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
        - Fn::Join:
            - ''
            - - 'arn:'
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: EcgStack/Credits/credits-api/CloudWatchRole/Resource
  CreditscreditsapiAccountF9FC1F5A:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - CreditscreditsapiCloudWatchRoleF4FE0D51
          - Arn
    DependsOn:
      - Creditscreditsapi548AF886
    Metadata:
      aws:cdk:path: EcgStack/Credits/credits-api/Account
  CreditscreditsapiDeploymentA812BC1357f276643a7d665b276eaeab5489ea89:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: Creditscreditsapi548AF886
      Description: Automatically created by the RestApi construct
    DependsOn:
      - CreditscreditsapicreditsPOSTB1F6BEFA
      - Creditscreditsapicredits3B160783
    Metadata:
      aws:cdk:path: EcgStack/Credits/credits-api/Deployment/Resource
  CreditscreditsapiDeploymentStageprodB9C9EA14:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: Creditscreditsapi548AF886
      DeploymentId:
        Ref: CreditscreditsapiDeploymentA812BC1357f276643a7d665b276eaeab5489ea89
      StageName: prod
    Metadata:
      aws:cdk:path: EcgStack/Credits/credits-api/DeploymentStage.prod/Resource
  Creditscreditsapicredits3B160783:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - Creditscreditsapi548AF886
          - RootResourceId
      PathPart: credits
      RestApiId:
        Ref: Creditscreditsapi548AF886
    Metadata:
      aws:cdk:path: EcgStack/Credits/credits-api/Default/credits/Resource
  CreditscreditsapicreditsPOSTApiPermissionEcgStackCreditscreditsapi1871A346POSTcredits08582E23:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - CreditsCreditsHandler3E4C260D
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ''
          - - 'arn:'
            - Ref: AWS::Partition
            - ':execute-api:'
            - Ref: AWS::Region
            - ':'
            - Ref: AWS::AccountId
            - ':'
            - Ref: Creditscreditsapi548AF886
            - /
            - Ref: CreditscreditsapiDeploymentStageprodB9C9EA14
            - /POST/credits
    Metadata:
      aws:cdk:path: EcgStack/Credits/credits-api/Default/credits/POST/ApiPermission.EcgStackCreditscreditsapi1871A346.POST..credits
  CreditscreditsapicreditsPOSTApiPermissionTestEcgStackCreditscreditsapi1871A346POSTcredits344CDBBE:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - CreditsCreditsHandler3E4C260D
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ''
          - - 'arn:'
            - Ref: AWS::Partition
            - ':execute-api:'
            - Ref: AWS::Region
            - ':'
            - Ref: AWS::AccountId
            - ':'
            - Ref: Creditscreditsapi548AF886
            - /test-invoke-stage/POST/credits
    Metadata:
      aws:cdk:path: EcgStack/Credits/credits-api/Default/credits/POST/ApiPermission.Test.EcgStackCreditscreditsapi1871A346.POST..credits
  CreditscreditsapicreditsPOSTB1F6BEFA:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      ResourceId:
        Ref: Creditscreditsapicredits3B160783
      RestApiId:
        Ref: Creditscreditsapi548AF886
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        RequestTemplates:
          application/json: '{ "statusCode": "200" }'
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ''
            - - 'arn:'
              - Ref: AWS::Partition
              - ':apigateway:'
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - CreditsCreditsHandler3E4C260D
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: EcgStack/Credits/credits-api/Default/credits/POST/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAAA1WQwVLDIBCGn6V3sjVWD95M63hTO/EJkKyVJECGBTsZJu9ugKStp//fneVb/i3h6QHKzTM/UyGabhuEsQjh03HRsYPR5KwXjlVE6ObmSeoTq5GMtwLZ4Vt/eDd4F92RW67QoY3F7chMaaSTRk8sbgm0g7D3osP0bHFZjqaXYry2cz2xnquvhhfaNNgSvCd59VpEKpNcQahNn5YlvWJWAO0KHiMQpCQLEMI8cuHEcbRKEuW/DvLEHZ75ONORXDXIJdlqKyGM14694NCbUaFOgW6qeLD0q2zWo+w54b8jXvwbuh/TxFZ20zSxGBpa2v6Wj1Dew92mJSkLOy+WCqHO+gez2uKOxwEAAA==
    Metadata:
      aws:cdk:path: EcgStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  CreditscreditsapiEndpoint96E3758D:
    Value:
      Fn::Join:
        - ''
        - - https://
          - Ref: Creditscreditsapi548AF886
          - .execute-api.
          - Ref: AWS::Region
          - '.'
          - Ref: AWS::URLSuffix
          - /
          - Ref: CreditscreditsapiDeploymentStageprodB9C9EA14
          - /
Parameters:
  AssetParameters85999cde342a3a55cb865b24fc98c0f87f12ed970badb944f4af9e6a009ccb3eS3Bucket2E82DD27:
    Type: String
    Description: S3 bucket for asset "85999cde342a3a55cb865b24fc98c0f87f12ed970badb944f4af9e6a009ccb3e"
  AssetParameters85999cde342a3a55cb865b24fc98c0f87f12ed970badb944f4af9e6a009ccb3eS3VersionKey614CE18A:
    Type: String
    Description: S3 key for asset version "85999cde342a3a55cb865b24fc98c0f87f12ed970badb944f4af9e6a009ccb3e"
  AssetParameters85999cde342a3a55cb865b24fc98c0f87f12ed970badb944f4af9e6a009ccb3eArtifactHash4D9295FB:
    Type: String
    Description: Artifact hash for asset "85999cde342a3a55cb865b24fc98c0f87f12ed970badb944f4af9e6a009ccb3e"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
