name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node 15.x and ubuntu-latest

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: npm run lint

      - name: Test CDK
        run: npm run test:cdk --ci --coverage --maxWorkers=2

      - name: Test SVG
        run: npm run test:svg --ci --coverage --maxWorkers=2
